### ISSUE TITLE
NaN from USD to EUR

### ISSUE THREAD

**Issue by desmeit** [paul-shuvo/nodejs-currency-converter#65]
Its not possible for me to use this package. I get an NaN result with my cloud function:

```
const currencyConverter = new CC({from: "USD, to: "EUR", amount: 9.99)});
const currencyconvert = await currencyConverter.convert();
console.log('currencyConverter', currencyconvert);
```

I tried also with 

```
request(`https://www.google.com/search?q=USD+to+EUR&hl=en`, function(error, response, body) {
    if (error) {
      return reject(error);
    } else {
     console.log(body);
    }
});
```

and get 

`Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><br>`

So what should I do?

Thanks

**Comment by paul-shuvo** [comment]
This package scrapes data and returns the conversation rates. That's why the package needs to be used on client side with the assumption that the client won't send so many requests. If you deploy it on servers side then all the requests would go through the same ip, thus you're getting this "unusual traffic" exception.
